config:
  global:
    scrape_interval: 10s

  scrape_configs:
    - job_name: node-exporter
      static_configs:
        - targets: ["node-exporter:9100"]
    - job_name: kube-state-metrics
      static_configs:
        - targets: ["kube-state-metrics:8080"]
