server:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: cloudflare
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.1.100/32"
    hosts:
      - host: vault.example.com
        paths: []
    tls:
      - secretName: vault-example-com-tls
        hosts:
          - vault.example.com

  standalone:
    enabled: "-"
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"

        telemetry {
          unauthenticated_metrics_access = true
        }
      }

      storage "file" {
        path = "/vault/data"
      }

      telemetry {
        prometheus_retention_time = "30s",
        disable_hostname = true
      }
