name: TFSec pipeline
on:
  push:
    paths:
      - 'modules/**'
      - 'examples/**'
  pull_request:
    types:
     - 'opened'
    paths:
      - 'modules/**'
      - 'examples/**'

jobs:
  tfsec:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
      name: Checkout source code

    - uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - run: go version
    - run: go env
    - run: go install github.com/aquasecurity/tfsec/cmd/tfsec@latest

    - name: Show version
      run: /home/runner/go/bin/tfsec --version

    - name: Run TFSec
      run: |
        CHANGE_FILE="/tmp/changes"
        git diff HEAD~1 --name-only -- modules | xargs dirname | sort | uniq > $CHANGE_FILE
        while read ROW
        do
          cd $GITHUB_WORKSPACE/$ROW
          /home/runner/go/bin/tfsec
          done < ${CHANGE_FILE}
